[tox]
min_version = 4.11
requires =
    tox-gh-actions>=3
envlist =
    python{3.11,3.12,3.13}-django{5.1,5.2}-wagtail{6.2,7.2}-{sqlite,postgres}
    python{3.12,3.13}-django6.0-wagtail7.2-{sqlite,postgres}
    pyright
skip_missing_interpreters = true

[gh-actions]
python =
    3.11: python3.11
    3.12: python3.12
    3.13: python3.13

[gh-actions:env]
DB =
    sqlite: sqlite
    postgres: postgres

[testenv]
package = editable
extras = test
commands = pytest -n auto --cov {posargs: -vv}

base_python =
    python3.11: python3.11
    python3.12: python3.12
    python3.13: python3.13

deps =
    django5.1: Django>=5.1,<5.2
    django5.2: Django>=5.2,<5.3
    django6.0: Django>=6.0,<6.1

    wagtail6.2: wagtail>=6.2,<6.3
    wagtail7.2: wagtail>=7.2,<7.3

    postgres: psycopg2>=2.9

setenv =
    postgres: DATABASE_URL={env:DATABASE_URL:postgres:///wagtail_localize_smartling}

[testenv:pyright]
allowlist_externals =
    pyright
commands = pyright {posargs}
