# Generated by Django 5.0.6 on 2024-05-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_synced_at", models.DateTimeField()),
                ("last_synced_at", models.DateTimeField()),
                ("account_uid", models.CharField(max_length=16)),
                ("archived", models.BooleanField()),
                ("project_id", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("type_code", models.CharField(max_length=16)),
                ("source_locale_description", models.CharField(max_length=255)),
                ("source_locale_id", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
                "unique_together": {("account_uid", "project_id")},
            },
        ),
        migrations.CreateModel(
            name="TargetLocale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale_id", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=255)),
                ("enabled", models.BooleanField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_locales",
                        to="wagtail_localize_smartling.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "locale_id")},
            },
        ),
    ]
