# Generated by Django 5.0.6 on 2024-05-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtail_localize", "0016_rename_page_revision_translationlog_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_synced_at", models.DateTimeField(editable=False, null=True)),
                ("last_synced_at", models.DateTimeField(editable=False, null=True)),
                ("account_uid", models.CharField(max_length=16)),
                ("archived", models.BooleanField()),
                ("project_id", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("type_code", models.CharField(max_length=16)),
                ("source_locale_description", models.CharField(max_length=255)),
                ("source_locale_id", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
                "unique_together": {("account_uid", "project_id")},
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_synced_at", models.DateTimeField(editable=False, null=True)),
                ("last_synced_at", models.DateTimeField(editable=False, null=True)),
                ("name", models.CharField(max_length=170)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "translation_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smartling_jobs",
                        to="wagtail_localize.translationsource",
                    ),
                ),
                (
                    "translations",
                    models.ManyToManyField(
                        related_name="smartling_jobs", to="wagtail_localize.translation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="wagtail_localize_smartling.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTargetLocale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale_id", models.CharField(max_length=16)),
                ("description", models.CharField(max_length=255)),
                ("enabled", models.BooleanField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_locales",
                        to="wagtail_localize_smartling.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "locale_id")},
            },
        ),
    ]
