# Generated by Django 5.0.6 on 2024-06-03 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize", "0016_rename_page_revision_translationlog_revision"),
        ("wagtail_localize_smartling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="status_consistent_with_sync_dates",
        ),
        migrations.AddField(
            model_name="job",
            name="reference_number",
            field=models.CharField(default="", editable=False, max_length=170),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("first_synced_at__isnull", True),
                        ("last_synced_at__isnull", True),
                        ("status", "UNSYNCED"),
                        ("translation_job_uid", ""),
                    ),
                    models.Q(
                        models.Q(("status", "UNSYNCED"), _negated=True),
                        ("first_synced_at__isnull", False),
                        ("last_synced_at__isnull", False),
                        models.Q(("translation_job_uid", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="status_consistent_with_sync_dates",
            ),
        ),
    ]
