# Generated by Django 5.0.6 on 2024-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_smartling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("AWAITING_AUTHORIZATION", "Awaiting authorization"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("CLOSED", "Closed"),
                    ("DELETED", "Deleted"),
                ],
                default="DRAFT",
                editable=False,
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="translation_job_uid",
            field=models.CharField(default="", editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
