# Generated by Django 5.0.6 on 2024-09-13 15:22
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_localize_smartling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
