# Generated by Django 5.1.3 on 2024-12-15 22:19

from django.db import migrations

from wagtail_localize_smartling.settings import settings as smartling_settings


def forwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=smartling_settings.TRANSLATION_APPROVER_GROUP_NAME)


def backwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name=smartling_settings.TRANSLATION_APPROVER_GROUP_NAME
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_localize_smartling", "0002_job_content_hash"),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            backwards,
        )
    ]
