# Generated by Django 5.0.6 on 2024-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_localize_smartling",
            "0002_remove_job_status_consistent_with_sync_dates_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="project",
            name="environment",
            field=models.CharField(default="production", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("environment", "account_uid", "project_id")},
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("environment", "production"),
                    ("environment", "staging"),
                    _connector="OR",
                ),
                name="project_environment",
            ),
        ),
    ]
