# Generated by Django 5.0.6 on 2024-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_localize_smartling",
            "0004_remove_job_reference_number_alter_job_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="file_uri",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
