name: Localize Smartling CI

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel tox tox-gh-actions
      - name: Pyright (Python ${{ matrix.python }})
        run: tox -e pyright -- --pythonversion ${{ matrix.python }}

  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
        django: ["4.2"]
        wagtail: ["6.2"]
        db: ["sqlite"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel tox tox-gh-actions
      - name: Test
        run: tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}-sqlite
          path: .coverage.*
          if-no-files-found: ignore
          retention-days: 1

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12']
    services:
      postgres:
        image: 'postgres:13'
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools wheel tox tox-gh-actions
      - name: Test
        run: tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize_smartling
          DB: postgres
